<?php
 
/**
 * EVEN FIBONACCI NUMBERS
 * 
 * Each new term in the Fibonacci Sequence is generated by adding the previous
 * two terms. By starting with 1 and 2, the first 10 terms will be:
 *
 * 				1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not 
 * exceed four million, find the sum of the even-valued terms.
 */

function evenFibonacci($limit) {
	$x = 0;
	$y = 1;
	$sum = 0;
	while ($x <= $limit) {
		//printf($x . "\n"); //print the fibonacci sequence
		$x = $y - $x;
		$y = $x + $y;
		if ($x % 2 == 0) {
			$sum += $x;
		}
	}
	return $sum;
}
echo evenFibonacci(4000000) . "\n";

?>
